### PR TITLE
Actually allow passing options to Swarm.

### PR DESCRIPTION
**Pull request by pvh**
Looks like you forgot something here?

### CODE REVIEW

**Comment by jwerle** [comment]
@pvh a hacky workaround:

```js
const { constructor: Swarm } = require('@hyperswarm/network')()
```

[this will create things](https://github.com/hyperswarm/network/blob/master/index.js#L16-L18) that may need to be destroyed :man_shrugging:

**Comment by mafintosh** [comment]
Nice catch. @jwerle you need the class exported?

**Comment by mafintosh** [comment]
0.0.0.4

**Comment by jwerle** [comment]
🙏 🙏
We'd love to properly extend this class instead of using the factory!

**Comment by mafintosh** [comment]
@jwerle would exports.Network be ok?

**Comment by jwerle** [comment]
@mafintosh Yeah that works !

**Pull request merged**
